{
    'name': 'IR',
    'active': True,
    'xml': [
        'ir.xml',
        'sequence.xml',
        'ui/ui.xml',
        'ui/menu.xml',
        'ui/view.xml',
        'actions.xml',
        'model.xml',
        'attachment.xml',
        'cron.xml',
        'values.xml',
        'translation.xml',
        'exports.xml',
        'rule.xml',
        'property.xml',
        'module/module.xml',
        'module/repository.xml',
        'module/category.xml',
        ],
}
